import type {
  User,
  Member,
  Session,
  Activity,
  SessionActivity,
  Attendance,
  AbsenceRequest,
  Topic,
  FCCProgression,
  Notification,
  Invitation,
  AppConfig,
  ActivitySelectionCycle,
  AuthUser,
  PendingRegistration,
  DebateTopic,
  SessionDebate,
} from "./types"

// Auth Users (with passwords for mock login)
export const authUsers: AuthUser[] = [
  {
    id: "1",
    email: "admin@englishclubs.com",
    password: "admin123", // In real app, this would be hashed
    firstName: "Jean",
    lastName: "Dupont",
    pseudo: "JeanD",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jean",
    englishLevel: "advanced",
    role: "admin",
    isEmailVerified: true,
    createdAt: new Date(2023, 0, 1).toISOString(),
    lastLoginAt: new Date().toISOString(),
  },
  {
    id: "2",
    email: "marie.martin@email.com",
    password: "membre123", // In real app, this would be hashed
    firstName: "Marie",
    lastName: "Martin",
    pseudo: "MarieM",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marie",
    englishLevel: "intermediate",
    role: "member",
    isEmailVerified: true,
    createdAt: new Date(2024, 0, 2).toISOString(),
    lastLoginAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Current user (admin) - you can switch to test different roles
export const currentUser: User = {
  id: "1",
  email: "admin@englishclubs.com",
  firstName: "Jean",
  lastName: "Dupont",
  pseudo: "JeanD",
  photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jean",
  englishLevel: "advanced",
  role: "admin",
}

// Pending registrations
export const pendingRegistrations: PendingRegistration[] = [
  {
    id: "pr1",
    email: "nouveau.membre@email.com",
    firstName: "Thomas",
    lastName: "Lefevre",
    pseudo: "ThomasL",
    englishLevel: "beginner",
    invitationToken: "abc123def456",
    status: "pending_admin",
    requestedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "pr2",
    email: "attente@email.com",
    firstName: "Julie",
    lastName: "Blanc",
    pseudo: "JulieB",
    englishLevel: "intermediate",
    status: "pending_email",
    requestedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Users
export const users: User[] = [
  currentUser,
  {
    id: "2",
    email: "marie.martin@email.com",
    firstName: "Marie",
    lastName: "Martin",
    pseudo: "MarieM",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marie",
    englishLevel: "intermediate",
    role: "member",
  },
  {
    id: "3",
    email: "pierre.bernard@email.com",
    firstName: "Pierre",
    lastName: "Bernard",
    pseudo: "PierreB",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pierre",
    englishLevel: "beginner",
    role: "member",
  },
  {
    id: "4",
    email: "sophie.durand@email.com",
    firstName: "Sophie",
    lastName: "Durand",
    pseudo: "SophieD",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie",
    englishLevel: "advanced",
    role: "member",
  },
  {
    id: "5",
    email: "lucas.moreau@email.com",
    firstName: "Lucas",
    lastName: "Moreau",
    pseudo: "LucasM",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    englishLevel: "intermediate",
    role: "member",
  },
  {
    id: "6",
    email: "emma.petit@email.com",
    firstName: "Emma",
    lastName: "Petit",
    pseudo: "EmmaP",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    englishLevel: "beginner",
    role: "member",
  },
  {
    id: "7",
    email: "hugo.robert@email.com",
    firstName: "Hugo",
    lastName: "Robert",
    pseudo: "HugoR",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hugo",
    englishLevel: "intermediate",
    role: "member",
  },
  {
    id: "8",
    email: "lea.simon@email.com",
    firstName: "Léa",
    lastName: "Simon",
    pseudo: "LeaS",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lea",
    englishLevel: "advanced",
    role: "member",
  },
]

// Members
export const members: Member[] = users.map((user, index) => ({
  id: `m${user.id}`,
  user,
  status: index === 5 ? "pending" : index === 6 ? "suspended" : "active",
  joinedAt: new Date(2024, 0, index + 1).toISOString(),
  // Deterministic values to avoid SSR/CSR hydration mismatches
  presenceCount: 8 + ((index * 3) % 17),
  absenceCount: (index + 1) % 5,
}))

// Activities - Complete predefined list
export const activities: Activity[] = [
  // === ICE BREAKERS (10-15 min) ===
  {
    id: "ice-1",
    name: "Two Truths and a Lie",
    nameEn: "Two Truths and a Lie",
    description: "Chacun dit 3 phrases sur soi, 2 vraies, 1 fausse. Les autres devinent laquelle est fausse.",
    category: "ice_breaker",
    defaultDuration: 10,
    minDuration: 10,
    maxDuration: 15,
    membersRequired: 3,
    selectionMode: "manual",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Chaque participant prepare 3 affirmations sur lui-meme (2 vraies, 1 fausse)\n2. A tour de role, chacun presente ses 3 phrases\n3. Les autres participants votent pour deviner le mensonge\n4. Le participant revele la reponse et peut raconter une anecdote",
    icon: "smile",
  },
  {
    id: "ice-2",
    name: "20 Questions",
    nameEn: "20 Questions",
    description: "Une personne pense a un mot, les autres ont 20 questions fermees pour deviner.",
    category: "ice_breaker",
    defaultDuration: 10,
    minDuration: 10,
    maxDuration: 15,
    membersRequired: 2,
    selectionMode: "automatic",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Un participant pense a un objet, une personne ou un lieu\n2. Les autres posent des questions OUI/NON uniquement\n3. Maximum 20 questions pour deviner\n4. Celui qui devine devient le prochain a penser",
    icon: "help-circle",
  },
  {
    id: "ice-3",
    name: "Word Chain",
    nameEn: "Word Chain",
    description: "Chaque personne dit un mot qui commence par la derniere lettre du mot precedent.",
    category: "ice_breaker",
    defaultDuration: 10,
    minDuration: 10,
    maxDuration: 15,
    membersRequired: 3,
    selectionMode: "manual",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Le premier joueur dit un mot en anglais\n2. Le joueur suivant doit dire un mot commencant par la derniere lettre\n3. Pas de repetition de mots\n4. 5 secondes max pour repondre\n5. Elimination si echec, le dernier gagne",
    icon: "link",
  },
  {
    id: "ice-4",
    name: "Hot Seat",
    nameEn: "Hot Seat",
    description: "Une personne s'assoit face au groupe et repond a 10 questions rapides en anglais.",
    category: "ice_breaker",
    defaultDuration: 15,
    minDuration: 10,
    maxDuration: 15,
    membersRequired: 1,
    selectionMode: "automatic",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Un participant s'assoit sur la 'hot seat'\n2. Le groupe pose 10 questions rapides (favorites, preferences, opinions)\n3. Reponses en 10 secondes max\n4. Questions fun et legeres recommandees\n5. Rotation apres chaque participant",
    icon: "flame",
  },
  {
    id: "ice-5",
    name: "Find Someone Who",
    nameEn: "Find Someone Who",
    description: "Grille a remplir en interrogeant les autres participants sur leurs experiences.",
    category: "ice_breaker",
    defaultDuration: 15,
    minDuration: 10,
    maxDuration: 15,
    membersRequired: 4,
    selectionMode: "manual",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Distribuer une grille avec des criteres (ex: has traveled abroad, speaks 3 languages...)\n2. Les participants circulent et posent des questions\n3. Noter le nom de la personne correspondant a chaque critere\n4. Le premier a completer la grille gagne\n5. Debrief collectif sur les decouvertes",
    icon: "users",
  },

  // === JEUX DE VOCABULAIRE (20-30 min) ===
  {
    id: "vocab-1",
    name: "Taboo",
    nameEn: "Taboo",
    description: "Faire deviner un mot sans utiliser 5 mots interdits associes.",
    category: "vocabulary",
    defaultDuration: 25,
    minDuration: 20,
    maxDuration: 30,
    membersRequired: 4,
    selectionMode: "manual",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Former 2 equipes\n2. Un joueur fait deviner un mot sans utiliser les 5 mots tabous\n3. 1 minute par tour\n4. 1 point par mot devine\n5. L'equipe adverse surveille les mots interdits",
    icon: "message-circle-off",
  },
  {
    id: "vocab-2",
    name: "Pictionary",
    nameEn: "Pictionary",
    description: "Dessiner un mot pour le faire deviner, les autres repondent en anglais.",
    category: "vocabulary",
    defaultDuration: 25,
    minDuration: 20,
    maxDuration: 30,
    membersRequired: 4,
    selectionMode: "manual",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Former 2 equipes\n2. Un joueur pioche un mot et le dessine (pas de lettres/chiffres)\n3. Son equipe doit deviner EN ANGLAIS\n4. 1 minute par dessin\n5. Alterner entre les equipes",
    materials: ["Tableau blanc ou papier", "Marqueurs", "Liste de mots"],
    icon: "pencil",
  },
  {
    id: "vocab-3",
    name: "Scattergories",
    nameEn: "Scattergories",
    description: "Une lettre, 5 categories, 2 minutes pour trouver un mot par categorie.",
    category: "vocabulary",
    defaultDuration: 20,
    minDuration: 20,
    maxDuration: 30,
    membersRequired: 2,
    selectionMode: "manual",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Tirer une lettre au hasard\n2. Presenter 5 categories (ex: Food, Country, Job, Animal, Object)\n3. 2 minutes pour ecrire un mot par categorie commencant par la lettre\n4. Lecture des reponses - mots uniques = 2 points, mots en commun = 1 point\n5. Plusieurs manches possibles",
    materials: ["Papier", "Stylos", "Chronometre"],
    icon: "grid",
  },
  {
    id: "vocab-4",
    name: "Vocabulary Auction",
    nameEn: "Vocabulary Auction",
    description: "Encherir sur des definitions - certaines sont correctes, d'autres non!",
    category: "vocabulary",
    defaultDuration: 25,
    minDuration: 20,
    maxDuration: 30,
    membersRequired: 3,
    selectionMode: "manual",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Chaque equipe recoit 1000$ fictifs\n2. L'animateur presente des definitions (vraies ou fausses)\n3. Les equipes encherissent sur les definitions qu'elles pensent correctes\n4. Les definitions correctes rapportent le double de la mise\n5. L'equipe la plus riche a la fin gagne",
    icon: "gavel",
  },
  {
    id: "vocab-5",
    name: "Charades",
    nameEn: "Charades",
    description: "Mimer un film, un metier, une action - les autres devinent en anglais.",
    category: "vocabulary",
    defaultDuration: 25,
    minDuration: 20,
    maxDuration: 30,
    membersRequired: 4,
    selectionMode: "automatic",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Former 2 equipes\n2. Un joueur pioche un mot/phrase et le mime (pas de paroles)\n3. Son equipe devine EN ANGLAIS\n4. 2 minutes maximum par mime\n5. Categories: films, metiers, actions, expressions",
    icon: "theater",
  },

  // === CONVERSATION STRUCTUREE (30-50 min) ===
  {
    id: "conv-1",
    name: "Speed Friending",
    nameEn: "Speed Friending",
    description: "Rotation de binomes toutes les 4 minutes avec une question imposee.",
    category: "conversation",
    defaultDuration: 40,
    minDuration: 30,
    maxDuration: 50,
    membersRequired: 6,
    selectionMode: "manual",
    requiresTopic: true,
    topicsReusable: true,
    isArchived: false,
    isDefault: true,
    instructions: "1. Placer les participants en 2 rangees face a face\n2. Donner une question de discussion a chaque round\n3. 4 minutes de conversation par binome\n4. Au signal, une rangee se decale d'une place\n5. Nouvelle question, nouveau partenaire",
    icon: "timer",
  },
  {
    id: "conv-2",
    name: "Fishbowl Discussion",
    nameEn: "Fishbowl Discussion",
    description: "4 personnes debattent au centre, les autres ecoutent puis prennent la releve.",
    category: "conversation",
    defaultDuration: 45,
    minDuration: 30,
    maxDuration: 50,
    membersRequired: 6,
    selectionMode: "semi-automatic",
    requiresTopic: true,
    topicsReusable: true,
    isArchived: false,
    isDefault: true,
    instructions: "1. 4 participants s'assoient au centre (fishbowl)\n2. Ils debattent du sujet pendant 10 minutes\n3. Les observateurs ne peuvent qu'ecouter\n4. Apres 10 min, un observateur peut taper l'epaule d'un participant pour prendre sa place\n5. Rotation jusqu'a ce que tous aient participe",
    icon: "circle",
  },
  {
    id: "conv-3",
    name: "Role Play",
    nameEn: "Role Play",
    description: "Scenarios imposes: client difficile, negociation, plainte a l'hotel, etc.",
    category: "conversation",
    defaultDuration: 40,
    minDuration: 30,
    maxDuration: 50,
    membersRequired: 2,
    selectionMode: "automatic",
    requiresTopic: true,
    topicsReusable: true,
    isArchived: false,
    isDefault: true,
    instructions: "1. Former des binomes ou petits groupes\n2. Distribuer les scenarios et roles\n3. 5 minutes de preparation\n4. 10 minutes de jeu de role\n5. Feedback du groupe sur le vocabulaire et la fluence",
    icon: "theater",
  },
  {
    id: "conv-4",
    name: "Desert Island",
    nameEn: "Desert Island",
    description: "Le groupe doit se mettre d'accord sur 5 objets a emporter sur une ile deserte.",
    category: "conversation",
    defaultDuration: 35,
    minDuration: 30,
    maxDuration: 45,
    membersRequired: 4,
    selectionMode: "manual",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Presenter le scenario: vous etes bloques sur une ile deserte\n2. Liste de 15 objets disponibles\n3. Le groupe doit choisir seulement 5 objets\n4. Debattre et argumenter EN ANGLAIS\n5. Consensus obligatoire - tout le monde doit etre d'accord",
    icon: "palmtree",
  },
  {
    id: "conv-5",
    name: "Mock Business Meeting",
    nameEn: "Mock Business Meeting",
    description: "Simulation de reunion professionnelle en anglais sur un projet fictif.",
    category: "conversation",
    defaultDuration: 45,
    minDuration: 30,
    maxDuration: 50,
    membersRequired: 4,
    selectionMode: "semi-automatic",
    requiresTopic: true,
    topicsReusable: true,
    isArchived: false,
    isDefault: true,
    instructions: "1. Distribuer les roles (CEO, Project Manager, Developer, Client...)\n2. Presenter l'ordre du jour de la reunion\n3. Conduire la reunion formellement en anglais\n4. Prendre des decisions, assigner des taches\n5. Rediger un compte-rendu rapide",
    materials: ["Cartes de roles", "Ordre du jour", "Template de compte-rendu"],
    icon: "briefcase",
  },

  // === COMPREHENSION ORALE ET ECRITE (20-40 min) ===
  {
    id: "comp-1",
    name: "Podcast Snippet",
    nameEn: "Podcast Snippet",
    description: "Ecoute d'un extrait (2 min) de BBC, Thinking in English ou VOA, puis discussion.",
    category: "comprehension",
    defaultDuration: 30,
    minDuration: 20,
    maxDuration: 40,
    membersRequired: 2,
    selectionMode: "manual",
    requiresTopic: true,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Jouer l'extrait de podcast (2-3 min)\n2. Premiere ecoute sans notes\n3. Deuxieme ecoute avec prise de notes\n4. Questions de comprehension\n5. Discussion ouverte sur le theme",
    materials: ["Extrait audio", "Questions preparees", "Enceinte/ecouteurs"],
    icon: "headphones",
  },
  {
    id: "comp-2",
    name: "TED-Ed Analysis",
    nameEn: "TED-Ed Analysis",
    description: "Video courte (4-5 min) suivie de questions et discussion de groupe.",
    category: "comprehension",
    defaultDuration: 35,
    minDuration: 25,
    maxDuration: 40,
    membersRequired: 2,
    selectionMode: "manual",
    requiresTopic: true,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Introduire le sujet de la video\n2. Regarder la video TED-Ed (4-5 min)\n3. Questions de comprehension\n4. Analyser les arguments presentes\n5. Debat: etes-vous d'accord avec le message?",
    materials: ["Video TED-Ed", "Projecteur", "Questions"],
    icon: "video",
  },
  {
    id: "comp-3",
    name: "News Headline Reading",
    nameEn: "News Headline Reading",
    description: "3 titres d'actualite africaine en anglais, chacun en choisit un et resume.",
    category: "comprehension",
    defaultDuration: 30,
    minDuration: 20,
    maxDuration: 35,
    membersRequired: 3,
    selectionMode: "automatic",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Presenter 3 articles d'actualite avec leurs titres\n2. Chaque participant choisit un article\n3. 5 minutes de lecture silencieuse\n4. Resume oral de l'article (2 min par personne)\n5. Questions et discussion de groupe",
    materials: ["Articles imprimes ou liens", "Chronometre"],
    icon: "newspaper",
  },
  {
    id: "comp-4",
    name: "Song Lyrics Gap Fill",
    nameEn: "Song Lyrics Gap Fill",
    description: "Texte a trous d'une chanson anglaise que le groupe complete a l'ecoute.",
    category: "comprehension",
    defaultDuration: 25,
    minDuration: 20,
    maxDuration: 30,
    membersRequired: 2,
    selectionMode: "manual",
    requiresTopic: false,
    topicsReusable: false,
    isArchived: false,
    isDefault: true,
    instructions: "1. Distribuer les paroles avec des mots manquants\n2. Premiere ecoute: essayer de completer\n3. Deuxieme ecoute: verifier et corriger\n4. Correction collective\n5. Discussion sur le sens de la chanson",
    materials: ["Paroles a trous", "Chanson audio", "Enceinte"],
    icon: "music",
  },

  // === PRODUCTION ECRITE (10-15 min) ===
  {
    id: "write-1",
    name: "One-Minute Writing",
    nameEn: "One-Minute Writing",
    description: "Ecrire sans s'arreter pendant 60 secondes sur un sujet donne, puis lire a voix haute.",
    category: "writing",
    defaultDuration: 10,
    minDuration: 10,
    maxDuration: 15,
    membersRequired: 1,
    selectionMode: "manual",
    requiresTopic: true,
    topicsReusable: true,
    isArchived: false,
    isDefault: true,
    instructions: "1. Donner le sujet (ex: 'My perfect day')\n2. REGLE: Ne jamais arreter d'ecrire pendant 60 secondes\n3. Pas de correction, pas de pause\n4. Lecture a voix haute volontaire\n5. Feedback positif sur le contenu",
    materials: ["Papier", "Stylos", "Chronometre"],
    icon: "edit",
  },
  {
    id: "write-2",
    name: "Six-Word Story",
    nameEn: "Six-Word Story",
    description: "Raconter une histoire complete en exactement 6 mots.",
    category: "writing",
    defaultDuration: 10,
    minDuration: 10,
    maxDuration: 15,
    membersRequired: 1,
    selectionMode: "manual",
    requiresTopic: true,
    topicsReusable: true,
    isArchived: false,
    isDefault: true,
    instructions: "1. Expliquer le concept (ex: Hemingway: 'For sale: baby shoes, never worn')\n2. Donner un theme ou laisser libre\n3. 5 minutes pour ecrire\n4. Chacun lit son histoire de 6 mots\n5. Voter pour les plus impactantes",
    materials: ["Papier", "Stylos"],
    icon: "file-text",
  },
  {
    id: "write-3",
    name: "Haiku Tech",
    nameEn: "Haiku Tech",
    description: "Composer un haiku en anglais sur un mot tech (5-7-5 syllabes).",
    category: "writing",
    defaultDuration: 10,
    minDuration: 10,
    maxDuration: 15,
    membersRequired: 1,
    selectionMode: "manual",
    requiresTopic: true,
    topicsReusable: true,
    isArchived: false,
    isDefault: true,
    instructions: "1. Expliquer la structure haiku (5-7-5 syllabes)\n2. Donner un mot tech (AI, Smartphone, Code...)\n3. 5 minutes pour composer\n4. Lecture des haikus\n5. Discussion sur les images evoquees",
    materials: ["Papier", "Stylos"],
    icon: "sparkles",
  },
  {
    id: "write-4",
    name: "Tweet That Idea",
    nameEn: "Tweet That Idea",
    description: "Resumer une idee complexe en 280 caracteres maximum en anglais.",
    category: "writing",
    defaultDuration: 10,
    minDuration: 10,
    maxDuration: 15,
    membersRequired: 1,
    selectionMode: "manual",
    requiresTopic: true,
    topicsReusable: true,
    isArchived: false,
    isDefault: true,
    instructions: "1. Presenter une idee ou un concept complexe\n2. Defi: le resumer en 280 caracteres max\n3. 5 minutes pour ecrire\n4. Partage des 'tweets'\n5. Discuter de ce qui a ete priorise",
    materials: ["Papier", "Stylos"],
    icon: "message-square",
  },
]

// Helper to find activity by id
const findActivity = (id: string) => activities.find(a => a.id === id)!

// Topics for activities that require them
export const topics: Topic[] = [
  // Topics for Speed Friending (conv-1)
  {
    id: "t1",
    activityId: "conv-1",
    activity: findActivity("conv-1"),
    title: "What's your biggest dream?",
    description: "Discuss your dreams and aspirations with your partner.",
    level: "beginner",
    isArchived: false,
    usageCount: 5,
  },
  {
    id: "t2",
    activityId: "conv-1",
    activity: findActivity("conv-1"),
    title: "If you could live anywhere...",
    description: "Where would you live and why?",
    level: "intermediate",
    isArchived: false,
    usageCount: 3,
  },
  // Topics for Fishbowl Discussion (conv-2)
  {
    id: "t3",
    activityId: "conv-2",
    activity: findActivity("conv-2"),
    title: "Remote work vs Office work",
    description: "Which is better for productivity and work-life balance?",
    level: "intermediate",
    isArchived: false,
    usageCount: 2,
  },
  {
    id: "t4",
    activityId: "conv-2",
    activity: findActivity("conv-2"),
    title: "AI will replace most jobs",
    description: "Debate whether artificial intelligence will make human workers obsolete.",
    level: "advanced",
    isArchived: false,
    usageCount: 1,
  },
  // Topics for Role Play (conv-3)
  {
    id: "t5",
    activityId: "conv-3",
    activity: findActivity("conv-3"),
    title: "Job interview simulation",
    description: "Practice a professional job interview in English.",
    level: "intermediate",
    isArchived: false,
    usageCount: 8,
  },
  {
    id: "t6",
    activityId: "conv-3",
    activity: findActivity("conv-3"),
    title: "Restaurant ordering scenario",
    description: "Practice ordering food and making requests at a restaurant.",
    level: "beginner",
    isArchived: false,
    usageCount: 10,
  },
  {
    id: "t7",
    activityId: "conv-3",
    activity: findActivity("conv-3"),
    title: "Hotel complaint scenario",
    description: "Handle a difficult situation at a hotel reception.",
    level: "intermediate",
    isArchived: false,
    usageCount: 4,
  },
  // Topics for Mock Business Meeting (conv-5)
  {
    id: "t8",
    activityId: "conv-5",
    activity: findActivity("conv-5"),
    title: "New product launch",
    description: "Plan the launch strategy for a new tech product.",
    level: "advanced",
    isArchived: false,
    usageCount: 2,
  },
  // Topics for Podcast Snippet (comp-1)
  {
    id: "t9",
    activityId: "comp-1",
    activity: findActivity("comp-1"),
    title: "BBC 6 Minute English - Technology",
    description: "Listen to a BBC podcast about modern technology trends.",
    level: "intermediate",
    isArchived: false,
    usageCount: 3,
  },
  // Topics for TED-Ed Analysis (comp-2)
  {
    id: "t10",
    activityId: "comp-2",
    activity: findActivity("comp-2"),
    title: "The power of introverts",
    description: "Susan Cain's famous TED talk on introversion.",
    level: "intermediate",
    isArchived: false,
    usageCount: 5,
  },
  // Topics for One-Minute Writing (write-1)
  {
    id: "t11",
    activityId: "write-1",
    activity: findActivity("write-1"),
    title: "My perfect day",
    description: "Describe what your ideal day would look like.",
    level: "beginner",
    isArchived: false,
    usageCount: 7,
  },
  // Topics for Six-Word Story (write-2)
  {
    id: "t12",
    activityId: "write-2",
    activity: findActivity("write-2"),
    title: "Love stories",
    description: "Write a 6-word story about love.",
    level: "intermediate",
    isArchived: false,
    usageCount: 4,
  },
  // Topics for Haiku Tech (write-3)
  {
    id: "t13",
    activityId: "write-3",
    activity: findActivity("write-3"),
    title: "Artificial Intelligence",
    description: "Write a haiku about AI.",
    level: "intermediate",
    isArchived: false,
    usageCount: 2,
  },
  // Topics for Tweet That Idea (write-4)
  {
    id: "t14",
    activityId: "write-4",
    activity: findActivity("write-4"),
    title: "Climate Change",
    description: "Summarize the climate crisis in 280 characters.",
    level: "advanced",
    isArchived: false,
    usageCount: 3,
  },
]

// Sessions
const today = new Date()
const nextWeek = new Date(today)
nextWeek.setDate(today.getDate() + 7)
const lastWeek = new Date(today)
lastWeek.setDate(today.getDate() - 7)

export const sessions: Session[] = [
  {
    id: "s1",
    date: nextWeek.toISOString().split("T")[0],
    startTime: "18:00",
    endTime: "20:00",
    status: "upcoming",
    createdBy: "1",
    activities: [],
    attendees: [],
  },
  {
    id: "s2",
    date: today.toISOString().split("T")[0],
    startTime: "18:00",
    endTime: "20:00",
    status: "ongoing",
    createdBy: "1",
    activities: [],
    attendees: [],
    startedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    currentActivityIndex: 1, // Second activity (index 1) is in progress
  },
  {
    id: "s3",
    date: lastWeek.toISOString().split("T")[0],
    startTime: "18:00",
    endTime: "20:00",
    status: "completed",
    createdBy: "1",
    activities: [],
    attendees: [],
  },
]

// Session Activities - Example session with activities from different categories
export const sessionActivities: SessionActivity[] = [
  // Session 1 - Upcoming session with full program
  {
    id: "sa1",
    sessionId: "s1",
    activity: findActivity("ice-1"), // Two Truths and a Lie
    orderIndex: 1,
    duration: 10,
    assignmentTiming: "before_event",
    assignments: [],
    status: "pending",
  },
  {
    id: "sa2",
    sessionId: "s1",
    activity: findActivity("vocab-1"), // Taboo
    orderIndex: 2,
    duration: 25,
    assignmentTiming: "before_event",
    assignments: [
      {
        id: "aa1",
        sessionActivityId: "sa2",
        user: users[1],
        assignmentType: "team_a",
        assignedBy: "1",
        assignedAt: new Date().toISOString(),
      },
      {
        id: "aa2",
        sessionActivityId: "sa2",
        user: users[2],
        assignmentType: "team_b",
        assignedBy: "1",
        assignedAt: new Date().toISOString(),
      },
    ],
    status: "pending",
  },
  {
    id: "sa3",
    sessionId: "s1",
    activity: findActivity("conv-3"), // Role Play
    orderIndex: 3,
    duration: 40,
    assignmentTiming: "before_event",
    topicId: "t5",
    topic: topics.find(t => t.id === "t5"),
    assignments: [
      {
        id: "aa3",
        sessionActivityId: "sa3",
        user: users[3],
        assignmentType: "interviewer",
        assignedBy: "1",
        assignedAt: new Date().toISOString(),
      },
      {
        id: "aa4",
        sessionActivityId: "sa3",
        user: users[4],
        assignmentType: "candidate",
        assignedBy: "1",
        assignedAt: new Date().toISOString(),
      },
    ],
    status: "pending",
  },
  // Session 2 - Ongoing session (first activity completed, second in progress)
  {
    id: "sa4",
    sessionId: "s2",
    activity: findActivity("ice-3"), // Word Chain
    orderIndex: 1,
    duration: 10,
    assignmentTiming: "before_event",
    assignments: [],
    status: "completed",
    startedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "sa5",
    sessionId: "s2",
    activity: findActivity("comp-2"), // TED-Ed Analysis
    orderIndex: 2,
    duration: 35,
    assignmentTiming: "during_event",
    topicId: "t10",
    topic: topics.find(t => t.id === "t10"),
    assignments: [],
    status: "in_progress",
    startedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "sa6",
    sessionId: "s2",
    activity: findActivity("write-1"), // One-Minute Writing
    orderIndex: 3,
    duration: 10,
    assignmentTiming: "during_event",
    topicId: "t11",
    topic: topics.find(t => t.id === "t11"),
    assignments: [],
    status: "pending",
  },
]

sessions[0].activities = sessionActivities.filter((sa) => sa.sessionId === "s1")
sessions[1].activities = sessionActivities.filter((sa) => sa.sessionId === "s2")

// Attendances
export const attendances: Attendance[] = [
  { id: "at1", sessionId: "s1", user: users[0], status: "declared", declaredAt: new Date().toISOString() },
  { id: "at2", sessionId: "s1", user: users[1], status: "declared", declaredAt: new Date().toISOString() },
  { id: "at3", sessionId: "s1", user: users[2], status: "declared", declaredAt: new Date().toISOString() },
  { id: "at4", sessionId: "s1", user: users[3], status: "excused" },
  {
    id: "at5",
    sessionId: "s2",
    user: users[0],
    status: "confirmed",
    declaredAt: new Date().toISOString(),
    confirmedAt: new Date().toISOString(),
    confirmedBy: "1",
  },
  {
    id: "at6",
    sessionId: "s2",
    user: users[1],
    status: "confirmed",
    declaredAt: new Date().toISOString(),
    confirmedAt: new Date().toISOString(),
    confirmedBy: "1",
  },
  { id: "at7", sessionId: "s2", user: users[2], status: "absent" },
  {
    id: "at8",
    sessionId: "s3",
    user: users[0],
    status: "confirmed",
    confirmedAt: lastWeek.toISOString(),
    confirmedBy: "1",
  },
  {
    id: "at9",
    sessionId: "s3",
    user: users[1],
    status: "confirmed",
    confirmedAt: lastWeek.toISOString(),
    confirmedBy: "1",
  },
  {
    id: "at10",
    sessionId: "s3",
    user: users[2],
    status: "confirmed",
    confirmedAt: lastWeek.toISOString(),
    confirmedBy: "1",
  },
  {
    id: "at11",
    sessionId: "s3",
    user: users[3],
    status: "confirmed",
    confirmedAt: lastWeek.toISOString(),
    confirmedBy: "1",
  },
]

sessions[0].attendees = attendances.filter((a) => a.sessionId === "s1")
sessions[1].attendees = attendances.filter((a) => a.sessionId === "s2")
sessions[2].attendees = attendances.filter((a) => a.sessionId === "s3")

// Absence Requests
export const absenceRequests: AbsenceRequest[] = [
  {
    id: "ar1",
    user: users[3],
    sessionId: "s1",
    session: sessions[0],
    reason: "Rendez-vous médical prévu de longue date.",
    status: "approved",
    adminComment: "Demande acceptée. Bon rétablissement !",
    requestedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: "1",
  },
  {
    id: "ar2",
    user: users[5],
    sessionId: "s1",
    session: sessions[0],
    reason: "Voyage professionnel imprévu.",
    status: "pending",
    requestedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ar3",
    user: users[4],
    sessionId: "s2",
    session: sessions[1],
    reason: "Événement familial.",
    status: "rejected",
    adminComment: "La demande a été faite trop tard (moins de 24h avant la séance).",
    requestedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    reviewedBy: "1",
  },
]

// FCC Progressions
export const fccProgressions: FCCProgression[] = [
  {
    id: "fcc1",
    user: users[1],
    track: "Responsive Web Design",
    level: "Completed",
    modulesCompleted: 5,
    certificateName: "Responsive Web Design Certificate",
    screenshotUrl: "/placeholder.svg",
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    validatedBy: "1",
    validatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fcc2",
    user: users[2],
    track: "JavaScript Algorithms and Data Structures",
    level: "In Progress",
    modulesCompleted: 3,
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fcc3",
    user: users[3],
    track: "Front End Development Libraries",
    level: "In Progress",
    modulesCompleted: 2,
    screenshotUrl: "/placeholder.svg",
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fcc4",
    user: users[4],
    track: "Responsive Web Design",
    level: "Starting",
    modulesCompleted: 1,
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fcc5",
    user: users[0],
    track: "Back End Development and APIs",
    level: "Completed",
    modulesCompleted: 5,
    certificateName: "Back End Development and APIs Certificate",
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    validatedBy: "1",
    validatedAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Notifications
export const notifications: Notification[] = [
  {
    id: "n1",
    userId: "1",
    type: "absence_request",
    title: "Nouvelle demande d'absence",
    body: "Emma Petit a soumis une demande d'absence pour la séance du " + nextWeek.toLocaleDateString("fr-FR"),
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n2",
    userId: "1",
    type: "membership_request",
    title: "Nouvelle demande d'adhésion",
    body: "Un nouvel utilisateur souhaite rejoindre la communauté.",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n3",
    userId: "1",
    type: "session_reminder",
    title: "Rappel de séance",
    body: "La prochaine séance aura lieu dans 24 heures.",
    isRead: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n4",
    userId: "1",
    type: "fcc_progress",
    title: "Nouvelle progression FreeCodeCamp",
    body: "Sophie Durand a mis à jour sa progression FreeCodeCamp.",
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Invitations
export const invitations: Invitation[] = [
  {
    id: "inv1",
    token: "abc123def456",
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
    createdAt: new Date().toISOString(),
  },
  {
    id: "inv2",
    token: "xyz789uvw012",
    email: "nouveau@email.com",
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "inv3",
    token: "expired123",
    expiresAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    usedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// App Config
export const appConfig: AppConfig = {
  id: "config1",
  appName: "English Club",
  accessType: "invitation",
  scheduleDays: ["saturday"],
  startTime: "18:00",
  endTime: "20:00",
  frequency: "weekly",
  rules:
    "1. Respectez les autres membres\n2. Parlez anglais pendant les séances\n3. Prévenez en cas d'absence\n4. Participez activement aux activités",
  absenceMinDelayHours: 24,
  fccReminderDays: 7,
}

// Activity Selection Cycles
export const activitySelectionCycles: ActivitySelectionCycle[] = [
  {
    id: "asc1",
    activityId: "a1",
    activity: activities[0],
    startedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    selections: [
      {
        id: "as1",
        cycleId: "asc1",
        userId: "2",
        user: users[1],
        sessionId: "s3",
        selectedAt: lastWeek.toISOString(),
      },
      {
        id: "as2",
        cycleId: "asc1",
        userId: "3",
        user: users[2],
        sessionId: "s2",
        selectedAt: today.toISOString(),
      },
    ],
  },
  {
    id: "asc2",
    activityId: "a2",
    activity: activities[1],
    startedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    selections: [
      {
        id: "as3",
        cycleId: "asc2",
        userId: "4",
        user: users[3],
        sessionId: "s3",
        selectedAt: lastWeek.toISOString(),
      },
    ],
  },
]

// Debate Topics
export const debateTopics: DebateTopic[] = [
  {
    id: "dt1",
    title: "Should social media be banned for teenagers?",
    description: "Discuss the pros and cons of social media usage among teenagers and whether restrictions should be implemented.",
    level: "intermediate",
    isArchived: false,
    usageCount: 3,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
  },
  {
    id: "dt2",
    title: "Remote work is better than office work",
    description: "Debate whether working from home provides more benefits than traditional office environments.",
    level: "intermediate",
    isArchived: false,
    usageCount: 5,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
  },
  {
    id: "dt3",
    title: "Artificial Intelligence will create more jobs than it destroys",
    description: "Explore the impact of AI on the job market and whether it's a threat or an opportunity.",
    level: "advanced",
    isArchived: false,
    usageCount: 2,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
  },
  {
    id: "dt4",
    title: "University education is still worth the investment",
    description: "Discuss whether traditional university education provides value for money in today's job market.",
    level: "intermediate",
    isArchived: false,
    usageCount: 4,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
  },
  {
    id: "dt5",
    title: "Electric vehicles should replace all gas-powered cars",
    description: "Debate the feasibility and desirability of transitioning entirely to electric vehicles.",
    level: "beginner",
    isArchived: false,
    usageCount: 1,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
  },
  {
    id: "dt6",
    title: "Space exploration is a waste of money",
    description: "Should governments prioritize space programs or redirect funds to solving Earth's problems?",
    level: "advanced",
    isArchived: false,
    usageCount: 0,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
  },
  {
    id: "dt7",
    title: "Fast food should be taxed like cigarettes",
    description: "Debate whether unhealthy food should face higher taxes to improve public health.",
    level: "beginner",
    isArchived: false,
    usageCount: 2,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
  },
  {
    id: "dt8",
    title: "Learning a second language should be mandatory",
    description: "Should all students be required to learn at least one foreign language?",
    level: "beginner",
    isArchived: false,
    usageCount: 6,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "1",
  },
]

// Session Debates
export const sessionDebates: SessionDebate[] = [
  {
    id: "sd1",
    sessionId: "s1",
    topic: debateTopics[2], // AI will create more jobs
    participantsCount: 4,
    selectedMembers: [users[1], users[2], users[3], users[4]],
    selectedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    selectedBy: "1",
    status: "selected",
  },
  {
    id: "sd2",
    sessionId: "s3",
    topic: debateTopics[1], // Remote work
    participantsCount: 3,
    selectedMembers: [users[0], users[1], users[3]],
    selectedAt: lastWeek.toISOString(),
    selectedBy: "1",
    status: "completed",
  },
]

// Assign debates to sessions
sessions[0].debate = sessionDebates.find(sd => sd.sessionId === "s1")
sessions[2].debate = sessionDebates.find(sd => sd.sessionId === "s3")

// Dashboard stats
export const dashboardStats = {
  totalMembers: members.filter((m) => m.status === "active").length,
  pendingMembers: members.filter((m) => m.status === "pending").length,
  suspendedMembers: members.filter((m) => m.status === "suspended").length,
  upcomingSessions: sessions.filter((s) => s.status === "upcoming").length,
  averageAttendanceRate: 85,
  pendingAbsenceRequests: absenceRequests.filter((ar) => ar.status === "pending").length,
  pendingFCCValidations: fccProgressions.filter((p) => !p.validatedAt).length,
  activeTopics: topics.filter((t) => !t.isArchived).length,
  usedTopics: topics.filter((t) => t.usageCount > 0).length,
}
